Repository exercism/8th, pull requests merged in 2024-05, with the labels that each got.

#187 spiral-matrix: sync
  exercises/practice/spiral-matrix/.docs/instructions.md
  exercises/practice/spiral-matrix/.docs/introduction.md
Labels: x:size/tiny

#188 anagram: sync
  exercises/practice/anagram/.docs/instructions.md
  exercises/practice/anagram/.docs/introduction.md
Labels: x:size/tiny

#191 housekeeping: sync filepaths (invalidators)
  exercises/practice/all-your-base/.meta/config.json
  exercises/practice/allergies/.meta/config.json
  exercises/practice/anagram/.meta/config.json
  exercises/practice/binary-search/.meta/config.json
  exercises/practice/diamond/.meta/config.json
  exercises/practice/difference-of-squares/.meta/config.json
  exercises/practice/dnd-character/.meta/config.json
  exercises/practice/flatten-array/.meta/config.json
  exercises/practice/food-chain/.meta/config.json
  exercises/practice/grains/.meta/config.json
  exercises/practice/high-scores/.meta/config.json
  exercises/practice/kindergarten-garden/.meta/config.json
  exercises/practice/knapsack/.meta/config.json
  exercises/practice/largest-series-product/.meta/config.json
  exercises/practice/list-ops/.meta/config.json
  exercises/practice/matching-brackets/.meta/config.json
  exercises/practice/matrix/.meta/config.json
  exercises/practice/meetup/.meta/config.json
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/parallel-letter-frequency/.meta/config.json
  exercises/practice/pascals-triangle/.meta/config.json
  exercises/practice/perfect-numbers/.meta/config.json
  exercises/practice/phone-number/.meta/config.json
  exercises/practice/protein-translation/.meta/config.json
  exercises/practice/proverb/.meta/config.json
  exercises/practice/rna-transcription/.meta/config.json
  exercises/practice/rotational-cipher/.meta/config.json
  exercises/practice/scrabble-score/.meta/config.json
  exercises/practice/secret-handshake/.meta/config.json
  exercises/practice/space-age/.meta/config.json
  exercises/practice/spiral-matrix/.meta/config.json
  exercises/practice/square-root/.meta/config.json
  exercises/practice/strain/.meta/config.json
  exercises/practice/sum-of-multiples/.meta/config.json
Labels: x:rep/tiny

#190 remove JSON literals from parallel-letter-frequency
  exercises/practice/parallel-letter-frequency/.meta/example.8th
Labels: x:rep/small

#189 knapsack: sync
  exercises/practice/knapsack/.docs/instructions.md
  exercises/practice/knapsack/.docs/introduction.md
Labels: x:size/tiny

#192 kindergarten-garden: sync
  exercises/practice/kindergarten-garden/.docs/instructions.md
  exercises/practice/kindergarten-garden/.docs/introduction.md
Labels: x:size/tiny
