Repository exercism/8th, pull requests merged in 2024-04, with the labels that each got.

#130 Sync recent prob-spec changes
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/darts/.meta/config.json
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/reverse-string/.meta/tests.toml
  exercises/practice/roman-numerals/.meta/tests.toml
  exercises/practice/roman-numerals/test.8th
Labels: x:rep/tiny

#149 Add command-line options to add-exercise script.
  bin/add-exercise
  bin/test
  bin/test-no-docker
Labels: x:rep/small

#162 yacht: sync
  exercises/practice/yacht/.docs/instructions.md
  exercises/practice/yacht/.docs/introduction.md
Labels: x:size/tiny
