Repository exercism/8th, pull requests merged in 2024-01, with the labels that each got.

#113 Sync fetch-configlet.ps1 script
  bin/fetch-configlet.ps1
Labels: x:size/tiny

#114 add notes about contributing
  README.md
Labels: x:rep/small

#115 Sync leap
  exercises/practice/leap/.docs/instructions.md
  exercises/practice/leap/.docs/introduction.md
  exercises/practice/leap/.meta/config.json
Labels: x:rep/tiny

#116 leap: sync
  exercises/practice/leap/.docs/introduction.md
Labels: x:size/tiny

#117 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#119 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny
